### ISSUE TITLE
Rename several this variables

### ISSUE THREAD

**Issue by nieltg** [nieltg/quickshoot-party-match-server#11]
[This](https://github.com/nieltg/quickshoot-party-match-server/blob/0c84680f093a6f943425d6653cd83b86f8f02baf/pkg/iohttp/handler.go#L21) shouldn't be `s`, but should be `h`. `s` is because that `struct` is previously named as `Server`, now it's named as `Handler`.

Let's make a convention here. This variable should be a full name of the `struct` or the initial letter of the `struct` name.

This is a refactoring issue. This can be done after #7 has merged.

**Comment by iamdejan** [comment]
Check [this commit](https://github.com/nieltg/quickshoot-party-match-server/commit/20212fa8465e4f9b1353cd15555d449e69e9768b). Is it enough? @nieltg

**Comment by nieltg** [comment]
The initial letter of the `struct` name is enough actually.

But, well, since you don't like that …
