### ISSUE TITLE
Use HTTP constants from http package

### ISSUE THREAD

**Issue by nieltg** [nieltg/quickshoot-party-match-server#8]
Use HTTP constants from [http](https://golang.org/pkg/net/http/#Handler) package in `iohttp`.

**Comment by nieltg** [comment]
Don't forget. In this example instruction, `writeHeader(500)`, there is an equivalent constant for the code 500 in the `http` package.

This one hasn't been handled yet.

**Comment by iamdejan** [comment]
Done
